create table exercises(
    id           bigserial primary key,
    created_at   timestamp with time zone,
    updated_at   timestamp with time zone,
    deleted_at   timestamp with time zone,
    bodyPart     VARCHAR(255),
    equipment    VARCHAR(255),
    gifUrl       TEXT,
    exerciseName VARCHAR(255),
    target       VARCHAR(255)
);

INSERT INTO exercises (bodyPart, equipment, gifUrl, exerciseName, target)
VALUES ('waist', 'body weight', 'https://v2.exercisedb.io/image/MOnK4iG0MEt9h8', '3/4 sit-up', 'abs'),
       ('waist', 'body weight', 'https://v2.exercisedb.io/image/PERWLDGUxVbpHS', '45° side bend', 'abs'),
       ('waist', 'body weight', 'https://v2.exercisedb.io/image/PLr4yo3j-f1amp', 'air bike', 'abs'),
       ('upper legs', 'body weight', 'https://v2.exercisedb.io/image/XPQwM7HECjgNFE', 'all fours squad stretch',
        'quads'),
       ('waist', 'body weight', 'https://v2.exercisedb.io/image/5nYph4eUGNiEdf', 'alternate heel touchers', 'abs'),
       ('back', 'cable', 'https://v2.exercisedb.io/image/Az5UYVYNa4j-oS', 'alternate lateral pulldown', 'lats'),
       ('lower legs', 'body weight', 'https://v2.exercisedb.io/image/ivmTcSJsMlXJeK', 'ankle circles', 'calves'),
       ('back', 'body weight', 'https://v2.exercisedb.io/image/LSBkdKcbK4xj8n', 'archer pull up', 'lats'),
       ('chest', 'body weight', 'https://v2.exercisedb.io/image/GSjHZGSiL1VbQ7', 'archer push up', 'pectorals'),
       ('waist', 'body weight', 'https://v2.exercisedb.io/image/osybi41Me6RFK2', 'arm slingers hanging bent knee legs',
        'abs'),
       ('waist', 'body weight', 'https://v2.exercisedb.io/image/yzS2EjySGDLmhh', 'arm slingers hanging straight legs',
        'abs'),
       ('upper legs', 'body weight', 'https://v2.exercisedb.io/image/sGs-MoFgyniLX4',
        'arms apart circular toe touch (male)', 'glutes'),
       ('waist', 'body weight', 'https://v2.exercisedb.io/image/WzINsIEOqFbBXG', 'arms overhead full sit-up (male)',
        'abs'),
       ('chest', 'leverage machine', 'https://v2.exercisedb.io/image/AbxK1fjW5YdIBj', 'assisted chest dip (kneeling)',
        'pectorals'),
       ('waist', 'assisted', 'https://v2.exercisedb.io/image/dgsJoe9nZI6G3Z', 'assisted hanging knee raise', 'abs'),
       ('waist', 'assisted', 'https://v2.exercisedb.io/image/apDkfV7kzgRGlV',
        'assisted hanging knee raise with throw down', 'abs'),
       ('lower legs', 'assisted', 'https://v2.exercisedb.io/image/FHWElls92kFz7u', 'assisted lying calves stretch',
        'calves'),
       ('upper legs', 'assisted', 'https://v2.exercisedb.io/image/pIPCvG-7PYwJyb', 'assisted lying glutes stretch',
        'glutes'),
       ('upper legs', 'assisted', 'https://v2.exercisedb.io/image/re-rcIyamJTP9k',
        'assisted lying gluteus and piriformis stretch', 'glutes'),
       ('waist', 'assisted', 'https://v2.exercisedb.io/image/tcoPW9l8mI0o23',
        'assisted lying leg raise with lateral throw down', 'abs'),
       ('waist', 'assisted', 'https://v2.exercisedb.io/image/bB-NQ-AJzljNQK',
        'assisted lying leg raise with throw down', 'abs'),
       ('waist', 'medicine ball', 'https://v2.exercisedb.io/image/QnFyADdqWwnFB5', 'assisted motion russian twist',
        'abs'),
       ('back', 'leverage machine', 'https://v2.exercisedb.io/image/dV2Lj3p2pfkt4c',
        'assisted parallel close grip pull-up', 'lats'),
       ('upper legs', 'assisted', 'https://v2.exercisedb.io/image/ytpSbFtNhvVICC', 'assisted prone hamstring',
        'hamstrings'),
       ('upper legs', 'assisted', 'https://v2.exercisedb.io/image/s55xDjQ5-0dYhP', 'assisted prone lying quads stretch',
        'quads'),
       ('waist', 'assisted', 'https://v2.exercisedb.io/image/KVV3sh0QGYv-NJ', 'assisted prone rectus femoris stretch',
        'abs'),
       ('back', 'leverage machine', 'https://v2.exercisedb.io/image/rFSbsEA3x-wTKy', 'assisted pull-up', 'lats'),
       ('chest', 'assisted', 'https://v2.exercisedb.io/image/V4PlYYE0rlK7tY',
        'assisted seated pectoralis major stretch with stability ball', 'pectorals'),
       ('upper legs', 'assisted', 'https://v2.exercisedb.io/image/OZz8IVRYN5EMiU',
        'assisted side lying adductor stretch', 'adductors'),
       ('waist', 'assisted', 'https://v2.exercisedb.io/image/XlUw13FKk3bpyO', 'assisted sit-up', 'abs'),
       ('back', 'leverage machine', 'https://v2.exercisedb.io/image/iD6I6vHUV4flxZ', 'assisted standing chin-up',
        'lats'),
       ('back', 'leverage machine', 'https://v2.exercisedb.io/image/FBiUSf5E1HdC7s', 'assisted standing pull-up',
        'lats'),
       ('upper arms', 'assisted', 'https://v2.exercisedb.io/image/qnqFpisTx9R-gB',
        'assisted standing triceps extension (with towel)', 'triceps'),
       ('upper arms', 'leverage machine', 'https://v2.exercisedb.io/image/Wr9I3UD5-miI3Y',
        'assisted triceps dip (kneeling)', 'triceps'),
       ('chest', 'leverage machine', 'https://v2.exercisedb.io/image/9RWiaQoGBGogXv',
        'assisted wide-grip chest dip (kneeling)', 'pectorals'),
       ('cardio', 'body weight', 'https://v2.exercisedb.io/image/GzvxMK5EkJ6H43', 'astride jumps (male)',
        'cardiovascular system'),
       ('cardio', 'body weight', 'https://v2.exercisedb.io/image/akGmnMj1gqgJU3', 'back and forth step',
        'cardiovascular system'),
       ('back', 'stability ball', 'https://v2.exercisedb.io/image/ukCeypFhLV0YC6', 'back extension on exercise ball',
        'spine'),
       ('back', 'body weight', 'https://v2.exercisedb.io/image/tbNQwmPPyh4Eds', 'back lever', 'upper back'),
       ('back', 'body weight', 'https://v2.exercisedb.io/image/RWvKeWqoM6lpAb', 'back pec stretch', 'lats'),
       ('upper legs', 'body weight', 'https://v2.exercisedb.io/image/HHJUonCfKdoEpz', 'backward jump', 'quads'),
       ('upper legs', 'body weight', 'https://v2.exercisedb.io/image/WDnFXk4aWMCJJi', 'balance board', 'quads'),
       ('upper arms', 'band', 'https://v2.exercisedb.io/image/y5DNwJsa0ZCGV3', 'band alternating biceps curl',
        'biceps'),
       ('waist', 'band', 'https://v2.exercisedb.io/image/3aZxWHvfEhzXVc', 'band alternating v-up', 'abs'),
       ('back', 'band', 'https://v2.exercisedb.io/image/dskU4kGOd518yz', 'band assisted pull-up', 'lats'),
       ('waist', 'band', 'https://v2.exercisedb.io/image/G-DQIUeMowP21I', 'band assisted wheel rollerout', 'abs'),
       ('chest', 'band', 'https://v2.exercisedb.io/image/oyWqo0D8zSMbyD', 'band bench press', 'pectorals'),
       ('upper legs', 'band', 'https://v2.exercisedb.io/image/IqkGQertTRdlLS', 'band bent-over hip extension',
        'glutes'),
       ('waist', 'band', 'https://v2.exercisedb.io/image/TLPldSbVb1qVb6', 'band bicycle crunch', 'abs');


